@startuml

hide circle
skinparam classAttributeIconSize 0

class CommandPart {
    +getStartIndex(): int
    +getEndIndex(): int
}
class CommandString {
    -commandText: String
    +toString(): String
}


CommandPart -right-> CommandString: refers to >

@enduml
